### ISSUE TITLE
Allow to input the brain mask

### ISSUE THREAD

**Issue by woctezuma** [bthyreau/hippodeep_pytorch#5]
Hello,

Thank you for the nice tool: light-weight, easy to install, very fast and it yields promising results!

I would have a minor suggestion: if a brain mask was already computed with another brain extraction tool, e.g. `HD-BET`, then the user might want to input the mask along the T1-weighted image. This would allow to skip the brain extraction step and rely on a potentially better brain extraction result.

Indeed, I have noticed that your brain extraction tool gives decent results, even better on my test example than [`BET`](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET) or [`ROBEX`](https://www.nitrc.org/projects/robex). However, [`HD-BET`](https://github.com/MIC-DKFZ/HD-BET) (published [in August 2019](https://doi.org/10.1002/hbm.24750), so a year and a half after [your paper](http://dx.doi.org/10.1016/j.media.2017.11.004)) gives slightly better results on my test example, along with convincing results in the paper itself. Plus, there may be even better tools for the brain extraction task in the future.

Would it make sense to allow to input the brain mask as a second argument to the script? Or is brain extraction not that crucial so that results should be good but don't need to be perfect for the rest of the process (registration to MNI152, bounding boxes encompassing the left and right hippocampi)?

**Edit:** Or an even simpler solution would be to add a flag to skip the brain extraction, assuming the T1-weighted image was already masked by the user. This way, the program would still be able to process multiple subjects. For instance:

```bash
deepseg1.sh --skip-brain-extraction subject_*_bet.nii.gz
```

vs. the current call:

```bash
deepseg1.sh subject_*.nii.gz
```

**Comment by bthyreau** [comment]
Thanks for your comment !

In fact, as you supposed, the brain-extraction here is not crucial. It is just output as a convenient, and hopefully robust way to get the total brain volume. The main goal is to get a spatially-consistent value (e.g. always clipping roughly the same location in the inferior slices) useful for statistical correction, but certainly not to get a pixel-perfect delineation. In population-analysis, an approximate brain size is generally ok (or even, as FreeSurfer does, a simple scaling factor).

Nice to learn that HD-BET is better for brain-extraction. Then I would definitely recommend to use it if an accurate brain segmentation is crucial for your task (e.g. a CSF quantification task).

Interestingly, reading your link, it is said that  HD-BET has been trained on a large variety of multi-contrast images, which is also what I did here. But as a major difference, HD-BET works at higher-res, while i purposely downsample at a low (yet meaningful) resolution to perform well on most CPU.

**Comment by woctezuma** [comment]
Thank you for the detailed reply!

And once again, thank you for the great tool! I will check your article in the _Medical Image Analysis_ journal. 😃
