### ISSUE TITLE
I can not load the module called "resource"

### ISSUE THREAD

**Issue by SDUELISUN123** [bthyreau/hippodeep_pytorch#7]
My computer system is Windows, and i can not import the module called "resource". But when i deleted the sentence "import resource" in .py, it could run normally and output the mask files i need. 
However, is it rigorous if i dont import it ?
Thanks for answering.

**Comment by bthyreau** [comment]
Hi,
Sure. Indeed "resource" is not a hard requirement, it is only used to monitor the ram consumption, for information purpose.
